version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/reports-frontend"
    schedule:
      interval: "monthly"
