# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
      - ci
      - dependencies
      - chore
    authors:
      - octocat
      - github-actions[bot]
      - github-actions
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"
