# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
      - cicd
      - dependencies
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"
